# Generated by Django 4.1.3 on 2023-02-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_home_service_app', '0002_alter_creditcard_card_cvv_alter_creditcard_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_home_service_app.take_appointment'),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register1',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
